version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "backend"
      - "frontend"
    ports:
      - 8080:80
    container_name: timed-unlock-reverse_proxy
  frontend:
    image: timed-unlock-frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=/api/
  backend:
    image: timed-unlock-backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - "mongo"
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - SECRET=SOMETHING_VERY_SECRET_FOR_JWT_SIGNING
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    
volumes:
  mongo_data: